version: '3.5'

services:
  pg:
    container_name: quizyy_postgres
    image: postgres
    env_file: .env
    ports:
      - "5431:5431"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
  app:
    container_name: quizyy
    image: xeoson/quizyy:0.1
    env_file: .env
    ports:
     - "3000:3000"
    depends_on:
      - pg
volumes:
  postgres_data: