version: '3.5'

services:
  pg:
    container_name: quizyy_postgres
    image: postgres
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    container_name: quizyy
    build: .
    env_file: .env
    ports:
     - "3000:3000"
    depends_on:
      - pg
volumes:
  postgres_data: