version: '3.5'

services:
  pg:
    container_name: quizyy_postgres
    image: postgres
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: