version: '3.5'

networks:
  quizyy:

services:
  pg:
    container_name: quizyy_postgres
    image: postgres
    env_file: .env
    networks:
      - quizyy
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
  app:
    container_name: quizyy
    build: .
    env_file: .env
    networks:
      - quizyy
    ports:
     - "3000:3000"
    depends_on:
      - pg
volumes:
  postgres_data: